import { readdirSync } from "node:fs";
import { join } from "node:path";
import { remove, writeIfChanged } from "../fsutil";
import { boxTokens, type Box, type Cube, type Row } from "../cube";
import { estimateTokens, fmtInt } from "../tokens";
import { DRAWERS } from "../format/drawers";
import type { CubeConfig } from "../config";
import { TOOL_COMMAND } from "../paths";

export const GENERATED_NOTE = "<!-- Generated by Context Cube. Don't edit: run `cube index` to rebuild. -->";

const TYPE_UNIT: Record<string, [string, string]> = {
  history: ["entry", "entries"],
  rules: ["rule", "rules"],
  invariants: ["topic", "topics"],
};

export function countLabel(row: Row): string {
  const [one, many] = TYPE_UNIT[row.type] ?? ["box", "boxes"];
  const n = row.boxes.length;
  return `${fmtInt(n)} ${n === 1 ? one : many}`;
}

export function rowTokens(row: Row, cpt: number): number {
  return [row.root, ...row.boxes].filter(Boolean).reduce((s, b) => s + boxTokens(b as Box, cpt), 0);
}

/** Boxes in the order a row index lists them: history newest first, others in order. */
export function listOrder(row: Row): Box[] {
  return row.type === "history" ? [...row.boxes].sort((a, b) => b.num - a.num) : row.boxes;
}

function drawerSizes(box: Box, cpt: number): string {
  return DRAWERS.filter((d) => box.drawers.some((x) => x.z === d.z))
    .map((d) => `Z${d.z} ~${fmtInt(estimateTokens(box.drawers.find((x) => x.z === d.z)!.chars, cpt))}`)
    .join(" · ");
}

/** What a status means for the reader. Stale means "verify", never "ignore". */
export function statusNote(rowType: string, status: string): string {
  if (status === "pending") return "CANDIDATE, not approved by a person: not a rule yet";
  if (status === "open") return "open: still collecting additions";
  if (status === "superseded") return "SUPERSEDED: a later decision replaced it; its last note says what's true now";
  const what = status === "stale" ? "its code changed since it was last checked" : "a code name it mentions is gone";
  if (rowType === "invariants") return `${status}: ${what}; the rule still holds, so check the code still follows it`;
  return `${status}: ${what}; check it against the code before relying on it`;
}

/** The file a migrated box's text came from ("quickie-video/PLAN.md L1-L40, ..." → "PLAN.md"). */
export function sourceFile(source: string | undefined): string | undefined {
  const m = /^([^,"]+?\.(?:md|markdown|txt|rst|adoc))(?:\s+L\d|,|$)/i.exec(source?.trim() ?? "");
  return m?.[1];
}

/** A plan, review, audit, handoff, or other document written at one moment, by its file name. */
export function isDatedDoc(file: string): boolean {
  const base = file.split("/").pop() ?? file;
  return /(?:^|[^a-z])(?:plans?|reviews?|audits?|handoffs?|prds?|proposals?|rfcs?|roadmaps?|todos?|specs?|retros?|postmortems?|brainstorm\w*|ideas?|drafts?)(?:[^a-z]|$)|\d{4}-\d{2}-\d{2}/i.test(base);
}

export function boxEntry(box: Box, cpt: number, rowType = ""): string {
  const h = box.header;
  const lines = [`### ${box.id} ${box.name}`];
  if (!h) {
    lines.push(`(header problem: ${box.doc?.error ?? "missing Z0"}; run \`cube check\`)`);
  } else {
    lines.push(h.summary);
    if (h.read_when) lines.push(`Read when: ${h.read_when}`);
  }
  const folder = box.relDir.split("/").pop();
  const extras = [drawerSizes(box, cpt)];
  const nLinks = h?.links.length ?? 0;
  if (nLinks) extras.push(`${nLinks} link${nLinks === 1 ? "" : "s"}`);
  if (h && h.status !== "ok") extras.push(statusNote(rowType, h.status));
  const from = rowType !== "history" && rowType !== "invariants" && rowType !== "rules" ? sourceFile(h?.source) : undefined;
  if (from && isDatedDoc(from)) extras.push(`from ${from.split("/").pop()} (dated: says what was meant or found then)`);
  lines.push(`Open: ${folder}/ · ${extras.filter(Boolean).join(" · ")}`);
  return lines.join("\n");
}

function rootSection(row: Row, cpt: number): string[] {
  const h = row.root?.header;
  const lines = [`# ${row.id} ${row.name}`, ""];
  if (!h) {
    lines.push("(this row has no valid root box; run `cube check`)", "");
    return lines;
  }
  lines.push(`Type: ${row.type} · ${countLabel(row)} · ~${fmtInt(rowTokens(row, cpt))} tokens in all`);
  lines.push("", h.summary);
  if (h.read_when) lines.push(`Open this row when: ${h.read_when}`);
  if (h.conventions?.length) lines.push("", "Conventions:", ...h.conventions.map((c) => `- ${c}`));
  if (row.type === "history") lines.push("", "Entries are past records. Where one disagrees with an invariant or the current code, the invariant and the code are current.");
  if (row.type === "invariants" && row.boxes.some((b) => b.header?.status === "pending")) {
    lines.push("", "Boxes marked CANDIDATE were proposed but not yet approved by a person. They aren't rules: don't follow or enforce them.");
  }
  const rootDrawers = row.root!.drawers.filter((d) => d.z !== 0);
  if (rootDrawers.length) {
    lines.push("", `Row-wide drawers: ${rootDrawers.map((d) => `X000-root/${d.file} (~${fmtInt(estimateTokens(d.chars, cpt))})`).join(", ")}`);
  }
  lines.push("");
  return lines;
}

export interface RowPage {
  file: string;
  text: string;
  first?: Box;
  last?: Box;
}

/** Splits a row index into pages at the token budget (plan 3.8). */
export function rowPages(row: Row, config: CubeConfig): RowPage[] {
  const cpt = config.tokens.charsPerToken;
  const budget = config.rowIndex.pageTokens;
  const head = rootSection(row, cpt);
  const entries = listOrder(row).map((b) => ({ box: b, text: boxEntry(b, cpt, row.type) }));
  const headTokens = estimateTokens(head.join("\n").length, cpt);
  const groups: { box: Box; text: string }[][] = [];
  let cur: { box: Box; text: string }[] = [];
  // Page 1 also carries the header and the page list; later pages carry a short title.
  let used = headTokens + 60;
  for (const e of entries) {
    const t = estimateTokens(e.text.length + 2, cpt);
    if (cur.length && used + t > budget) {
      groups.push(cur);
      cur = [];
      used = 30;
    }
    cur.push(e);
    used += t;
  }
  if (cur.length || !groups.length) groups.push(cur);

  const pageFile = (i: number) => (i === 0 ? "ROW.md" : `ROW-p${i + 1}.md`);
  const range = (g: { box: Box }[]) => (g.length ? `${g[0].box.id.split(".")[1]}–${g[g.length - 1].box.id.split(".")[1]}` : "none");
  const pages: RowPage[] = groups.map((g, i) => {
    const lines: string[] = [GENERATED_NOTE];
    if (i === 0) {
      lines.push(...head);
      if (groups.length > 1) {
        lines.push(`This index has ${groups.length} pages. This is page 1 (${range(g)}${row.type === "history" ? ", newest" : ""}).`);
        for (let k = 1; k < groups.length; k++) lines.push(`- ${pageFile(k)}: ${range(groups[k])}`);
        lines.push("");
      }
    } else {
      lines.push(`# ${row.id} ${row.name}: page ${i + 1} of ${groups.length} (${range(g)})`, "", `Page 1 and the row overview: ROW.md`, "");
    }
    if (!g.length && i === 0) lines.push("No boxes yet.");
    lines.push(g.map((e) => e.text).join("\n\n"));
    return { file: pageFile(i), text: `${lines.join("\n").replace(/\n+$/, "")}\n`, first: g[0]?.box, last: g[g.length - 1]?.box };
  });
  return pages;
}

export function writeRowPages(row: Row, config: CubeConfig): number {
  const pages = rowPages(row, config);
  let changed = 0;
  const keep = new Set(pages.map((p) => p.file));
  for (const p of pages) if (writeIfChanged(join(row.dir, p.file), p.text)) changed++;
  for (const f of readdirSync(row.dir)) {
    if (/^ROW(-p\d+)?\.md$/.test(f) && !keep.has(f)) {
      remove(join(row.dir, f));
      changed++;
    }
  }
  return changed;
}

export const PROTOCOL = [
  "1. Follow every rule in the rules row (already loaded; a rule scoped to certain files loads when you work with them).",
  "2. Use the row list to decide which rows could matter for the task.",
  "3. Open the row index (ROW.md) of each one. Start with page 1; open other pages only if needed.",
  `4. Open drawers only as each box's read-when line says. Before editing a file, open Z1 for every invariant linked to it: \`${TOOL_COMMAND} related <file>\` lists them, with the boxes and history linked to the file.`,
  "5. Follow a link only when its note answers a question your task raises. Everything you open stays in your context for the rest of the session, so don't read around.",
  "6. History entries are past records. Where one disagrees with an invariant or the current code, the invariant and the code are current. Invariants marked CANDIDATE aren't approved yet and aren't rules.",
  `7. Notes moved in from plans, reviews, and handoffs (marked "dated") say what was meant or found when they were written; history after them and the code say what shipped. A box marked SUPERSEDED was replaced by a later decision, and its last note says what's current. When you find a note that later history or the code contradicts, mark it: \`${TOOL_COMMAND} supersede <id> --by <history entry> --note "<what's true now>"\`.`,
  `8. To search the memory, use \`${TOOL_COMMAND} find <words>\`, not a search of the whole project.`,
  `9. Create rows, boxes, and history entries only with cube commands (\`${TOOL_COMMAND} <command>\`). Never pick coordinates yourself.`,
  `10. Never edit invariant text directly. Use \`${TOOL_COMMAND} propose\`.`,
  `11. Text moved in from the project's original files, and closed history entries, are records: add to them with \`${TOOL_COMMAND} write <id> Z4 --append\`; never rewrite or shorten them. Notes added later are dated and come after the text; where one disagrees with the text above it, the latest note is current.`,
];

/**
 * One row in a row list. `compact` keeps only the name and when to open it (the
 * routing instruction), for an always-loaded block over its ceiling.
 */
export function rowListLine(row: Row, cpt: number, withPath: string, sizes = true, compact = false): string {
  const h = row.root?.header;
  const summary = h ? h.summary : "(no root summary)";
  if (compact) return `- ${row.id} ${row.name}: open when ${h?.read_when ? h.read_when.replace(/^./, (c) => c.toLowerCase()) : summary} → ${withPath}${row.relDir}/ROW.md`;
  const when = h?.read_when ? ` Open when: ${h.read_when}` : "";
  const size = sizes ? ` (${countLabel(row)}, ~${fmtInt(rowTokens(row, cpt))} tokens)` : "";
  return `- ${row.id} ${row.name}: ${summary}${when}${size} → ${withPath}${row.relDir}/ROW.md`;
}

export function cubeMd(cube: Cube, config: CubeConfig): string {
  const cpt = config.tokens.charsPerToken;
  const lines = [
    GENERATED_NOTE,
    "# Project memory (Context Cube)",
    "",
    "This folder is the project's memory: rules, history, invariants (rules that must never be broken), features, systems, and anything else worth remembering. Read it top-down: short summaries first, detail only when a task needs it.",
    "",
    "## How to read it",
    "",
    ...PROTOCOL,
    "",
    "## Layout",
    "",
    "- A **row** (Y00–Y99) is one area: rules, history, invariants, a feature, a system, or a catalog. Y00 is always the rules row.",
    "- A **box** (X001…) is one item in a row. X000 is the row's root, describing the whole row.",
    "- Every box has the same five **drawers**: Z0 overview (with a read-when line), Z1 invariants, Z2 code, Z3 history, Z4 detail. Only Z0 is required.",
    "- Ids look like `Y05.X003` (a box) and `Y05.X003.Z1` (a drawer). Inline references look like `[[Y05.X003]]`.",
    `- Old references such as "§21" resolve with \`${TOOL_COMMAND} resolve "§21"\`.`,
    "",
    "## Rows",
    "",
  ];
  if (!cube.rows.length) lines.push("No rows yet.");
  for (const row of cube.rows) lines.push(rowListLine(row, cpt, ""));
  lines.push("", "## Commands", "", `Run from the project root: \`${TOOL_COMMAND} <command>\`. \`${TOOL_COMMAND} --help\` lists them all.`, "");
  return `${lines.join("\n")}`;
}
